language: ruby
sudo: required
git:
  depth: 9999
branches:
  except:
    - "/^[0-9]/"
services:
  - docker
before_install:
  - |
    if [ "$TRAVIS_PULL_REQUEST" != "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then
      echo "Do not open PRs against master; merge dev into master locally and push instead."
      exit 1
    fi
  - export DOCKER_IMAGE_TAG=26883287a66ab708b84c522c588967e78e8473d9
  - export ARTIFACT_VERSION=$(git rev-list --count HEAD)
  - export TERM=dumb
  - docker pull stoyicker/docker-android:${DOCKER_IMAGE_TAG}
  - docker tag stoyicker/docker-android:${DOCKER_IMAGE_TAG} stoyicker/docker-android
  - export CONTAINER=$(docker run -dt -p 127.0.0.1:80:4567 -e CI -e ARTIFACT_VERSION -e TERM -e TRAVIS_BRANCH -e REPO_USER -e GITHUB_TOKEN -e TRAVIS_REPO_SLUG stoyicker/docker-android)
  - docker exec -t $CONTAINER /bin/sh -c "mkdir -p /root/${TRAVIS_REPO_SLUG}"
  - docker cp ./ $CONTAINER:root/${TRAVIS_REPO_SLUG}
env:
  matrix:
  - TASK="\"./gradlew :app:build -Dhttp.socketTimeout=120000 -Dhttp.connectionTimeout=120000 --no-daemon\""
script:
  - docker exec -it $CONTAINER /bin/sh -c "cd root/${TRAVIS_REPO_SLUG}; ./_ci/script.sh ${TASK}"
after_success:
  - |
    if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]]; then
      echo "CI on master succeded. Executing release tasks..."
      docker exec -t $CONTAINER /bin/sh -c "cd root/${TRAVIS_REPO_SLUG}; ./_ci/release.sh"
    fi
notifications:
  email:
    recipients:
      jorge.diazbenitosoriano@gmail.com
    on_success:
      never
    on_failure:
      change
